baseURL = "https://th0th.dev"
languageCode = "en-us"
title = "th0th"
theme = "musings"

enableRobotsTXT = true
enableEmoji = true

[pagination]
pagerSize = 8

[taxonomies]
tag = "tags"
series = "series"

[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
description = "th0th"
author = "th0th"
githubURL = "https://github.com/alexrf45"
spotifyURL = "https://open.spotify.com/user/22gfjmri5pyghz74jnktm5xzi"
spotifyName = "Alexander Sean"
