#baseURL = "https://blog.joway.io/"
languageCode = "en-us"
title = "Musings of Fr3d"
theme = "yinyang"
DefaultContentLanguage = "en"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
guessSyntax = true
noClasses = true
style = "bw"
tabWidth = 2

[author]
name = "fr3d"
homepage = "https://blog.fr3d.dev"

[languages]
[languages.en]
contentDir = "/content"
languageName = "English"
weight = 1

[params]
mainSections = ["posts"]
headTitle = "Fr3d"
#extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'

[[params.socials]]
name = "About Me"
link = "https://blog.fr3d.dev"
[[params.socials]]
name = "Github"
link = "https://github.com/alexrf45"
postHeaderContent = ""
#postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []
