"""add featured to posts

Revision ID: 060ca103291f
Revises: 4bb407d2cc28
Create Date: 2026-03-13 17:15:49.293923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060ca103291f'
down_revision = '4bb407d2cc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
