name: Build Website Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency: production
jobs:
  prepare_tag:
    outputs:
      tag: ${{ steps.semver.outputs.next }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          fallbackTag: 'v1.0.0'
          additionalCommits: 'docs,update'
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.next }}
          tag_prefix: ""
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: prepare_tag
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Job Start
        uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#docker-build'
          message: Starting blog.fr3d.dev build and push...

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: 'fonalex45/blog:${{ needs.prepare_tag.outputs.tag }}'
      - name: Notify Slack Channel of finished build
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: '#docker-build'
          message: BUILD COMPLETE for blog.fr3d.dev {{env.GITHUB_REF_NAME }}
        if: always()
