name: Build Website Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Job Start
        uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#docker-build'
          message: Starting blog.fr3d.dev build and push...

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: 'fonalex45/blog:latest'
      
      - name: Notify Slack Channel of finished build
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: '#docker-build'
          message: BUILD COMPLETE for blog.fr3d.dev {{env.GITHUB_REF_NAME }}
        if: always()
